# Generated by Django 2.2.2 on 2019-06-07 14:44

from django.db import migrations, models
import validators.phone_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_to', models.CharField(max_length=10, validators=[validators.phone_validator.validate_phone])),
                ('is_missed', models.BooleanField(default=True)),
                ('made_on', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('msg', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(max_length=10, validators=[validators.phone_validator.validate_phone])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('is_fav', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Mobile', 'Mobile'), ('Work', 'Work'), ('Home', 'Home'), ('Fax', 'Fax')], default='Mobile', max_length=15)),
            ],
        ),
    ]
